<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE HealthData [
<!-- HealthKit Export Version: 3 -->
<!ELEMENT HealthData (ExportDate,Me,(Record|Correlation|Workout|ActivitySummary)*)>
<!ATTLIST HealthData
  locale CDATA #REQUIRED
>
<!ELEMENT ExportDate EMPTY>
<!ATTLIST ExportDate
  value CDATA #REQUIRED
>
<!ELEMENT Me EMPTY>
<!ATTLIST Me
  HKCharacteristicTypeIdentifierDateOfBirth         CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBiologicalSex       CDATA #REQUIRED
  HKCharacteristicTypeIdentifierBloodType           CDATA #REQUIRED
  HKCharacteristicTypeIdentifierFitzpatrickSkinType CDATA #REQUIRED
>
<!ELEMENT Record (MetadataEntry*)>
<!ATTLIST Record
  type          CDATA #REQUIRED
  unit          CDATA #IMPLIED
  value         CDATA #IMPLIED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!-- Note: Any Records that appear as children of a correlation also appear as top-level records in this document. -->
<!ELEMENT Correlation ((MetadataEntry|Record)*)>
<!ATTLIST Correlation
  type          CDATA #REQUIRED
  sourceName    CDATA #REQUIRED
  sourceVersion CDATA #IMPLIED
  device        CDATA #IMPLIED
  creationDate  CDATA #IMPLIED
  startDate     CDATA #REQUIRED
  endDate       CDATA #REQUIRED
>
<!ELEMENT Workout ((MetadataEntry|WorkoutEvent)*)>
<!ATTLIST Workout
  workoutActivityType   CDATA #REQUIRED
  duration              CDATA #IMPLIED
  durationUnit          CDATA #IMPLIED
  totalDistance         CDATA #IMPLIED
  totalDistanceUnit     CDATA #IMPLIED
  totalEnergyBurned     CDATA #IMPLIED
  totalEnergyBurnedUnit CDATA #IMPLIED
  sourceName            CDATA #REQUIRED
  sourceVersion         CDATA #IMPLIED
  device                CDATA #IMPLIED
  creationDate          CDATA #IMPLIED
  startDate             CDATA #REQUIRED
  endDate               CDATA #REQUIRED
>
<!ELEMENT WorkoutEvent EMPTY>
<!ATTLIST WorkoutEvent
  type CDATA #REQUIRED
  date CDATA #REQUIRED
>
<!ELEMENT ActivitySummary EMPTY>
<!ATTLIST ActivitySummary
  dateComponents           CDATA #IMPLIED
  activeEnergyBurned       CDATA #IMPLIED
  activeEnergyBurnedGoal   CDATA #IMPLIED
  activeEnergyBurnedUnit   CDATA #IMPLIED
  appleExerciseTime        CDATA #IMPLIED
  appleExerciseTimeGoal    CDATA #IMPLIED
  appleStandHours          CDATA #IMPLIED
  appleStandHoursGoal      CDATA #IMPLIED
>
<!ELEMENT MetadataEntry EMPTY>
<!ATTLIST MetadataEntry
  key   CDATA #REQUIRED
  value CDATA #REQUIRED
>
]>
<HealthData locale="en_US">
 <ExportDate value="2016-12-08 09:53:48 -0800"/>
 <Me HKCharacteristicTypeIdentifierDateOfBirth="1986-12-05" HKCharacteristicTypeIdentifierBiologicalSex="HKBiologicalSexMale" HKCharacteristicTypeIdentifierBloodType="HKBloodTypeNotSet" HKCharacteristicTypeIdentifierFitzpatrickSkinType="HKFitzpatrickSkinTypeNotSet"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="Andrew Bishara’s iPhone" sourceVersion="10.1.1" unit="ft" creationDate="2016-12-05 20:44:06 -0800" startDate="2016-12-05 20:44:06 -0800" endDate="2016-12-05 20:44:06 -0800" value="5.83333"/>
 <Record type="HKQuantityTypeIdentifierHeight" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" unit="ft" creationDate="2016-12-05 20:59:59 -0800" startDate="2016-12-05 20:59:59 -0800" endDate="2016-12-05 20:59:59 -0800" value="5.83333"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Andrew Bishara’s iPhone" sourceVersion="10.1.1" unit="lb" creationDate="2016-12-05 20:44:06 -0800" startDate="2016-12-05 20:44:06 -0800" endDate="2016-12-05 20:44:06 -0800" value="195"/>
 <Record type="HKQuantityTypeIdentifierBodyMass" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" unit="lb" creationDate="2016-12-05 20:59:59 -0800" startDate="2016-12-05 20:59:59 -0800" endDate="2016-12-05 20:59:59 -0800" value="195"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x1742813b0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 20:59:19 -0800" startDate="2016-12-05 20:59:19 -0800" endDate="2016-12-05 20:59:19 -0800" value="67"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x174280190&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 20:59:24 -0800" startDate="2016-12-05 20:59:24 -0800" endDate="2016-12-05 20:59:24 -0800" value="65"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x1742810e0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 20:59:30 -0800" startDate="2016-12-05 20:59:30 -0800" endDate="2016-12-05 20:59:30 -0800" value="65"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x174280f00&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 20:59:35 -0800" startDate="2016-12-05 20:59:34 -0800" endDate="2016-12-05 20:59:34 -0800" value="65"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x174280c80&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 20:59:40 -0800" startDate="2016-12-05 20:59:40 -0800" endDate="2016-12-05 20:59:40 -0800" value="67"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x174282b70&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 20:59:45 -0800" startDate="2016-12-05 20:59:45 -0800" endDate="2016-12-05 20:59:45 -0800" value="65"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x1742805f0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 20:59:50 -0800" startDate="2016-12-05 20:59:47 -0800" endDate="2016-12-05 20:59:47 -0800" value="67"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x17409c4d0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 20:59:55 -0800" startDate="2016-12-05 20:59:53 -0800" endDate="2016-12-05 20:59:53 -0800" value="65"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x174099190&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 21:00:00 -0800" startDate="2016-12-05 20:59:56 -0800" endDate="2016-12-05 20:59:56 -0800" value="65"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x1742841a0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 21:00:05 -0800" startDate="2016-12-05 21:00:04 -0800" endDate="2016-12-05 21:00:04 -0800" value="65"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x174281e00&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 21:00:10 -0800" startDate="2016-12-05 21:00:10 -0800" endDate="2016-12-05 21:00:10 -0800" value="65"/>
 <Record type="HKQuantityTypeIdentifierHeartRate" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x1742834d0&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" unit="count/min" creationDate="2016-12-05 21:00:16 -0800" startDate="2016-12-05 21:00:11 -0800" endDate="2016-12-05 21:00:11 -0800" value="65"/>
 <Record type="HKCategoryTypeIdentifierAppleStandHour" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" device="&lt;&lt;HKDevice: 0x174299370&gt;, name:Apple Watch, manufacturer:Apple, model:Watch, hardware:Watch2,4, software:3.1&gt;" creationDate="2016-12-08 09:06:26 -0800" startDate="2016-12-08 09:00:00 -0800" endDate="2016-12-08 10:00:00 -0800" value="HKCategoryValueAppleStandHourStood"/>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" creationDate="2016-12-06 05:21:41 -0800" startDate="2016-12-06 05:20:37 -0800" endDate="2016-12-06 05:21:37 -0800">
  <MetadataEntry key="_HKPrivateDeepBreathingEndReason" value="1"/>
  <MetadataEntry key="_HKPrivateDeepBreathingFinalHeartRate" value="70.17866516113281"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" creationDate="2016-12-06 21:41:03 -0800" startDate="2016-12-06 21:40:00 -0800" endDate="2016-12-06 21:41:00 -0800">
  <MetadataEntry key="_HKPrivateDeepBreathingEndReason" value="1"/>
  <MetadataEntry key="_HKPrivateDeepBreathingFinalHeartRate" value="63.173583984375"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" creationDate="2016-12-06 21:42:24 -0800" startDate="2016-12-06 21:41:21 -0800" endDate="2016-12-06 21:42:21 -0800">
  <MetadataEntry key="_HKPrivateDeepBreathingEndReason" value="1"/>
  <MetadataEntry key="_HKPrivateDeepBreathingFinalHeartRate" value="68.49722290039062"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" creationDate="2016-12-07 05:43:48 -0800" startDate="2016-12-07 05:42:45 -0800" endDate="2016-12-07 05:43:45 -0800">
  <MetadataEntry key="_HKPrivateDeepBreathingEndReason" value="1"/>
  <MetadataEntry key="_HKPrivateDeepBreathingFinalHeartRate" value="50.37675857543945"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" creationDate="2016-12-07 11:33:40 -0800" startDate="2016-12-07 11:32:37 -0800" endDate="2016-12-07 11:33:37 -0800">
  <MetadataEntry key="_HKPrivateDeepBreathingEndReason" value="1"/>
  <MetadataEntry key="_HKPrivateDeepBreathingFinalHeartRate" value="73.10501861572266"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" creationDate="2016-12-07 16:36:00 -0800" startDate="2016-12-07 16:34:57 -0800" endDate="2016-12-07 16:35:57 -0800">
  <MetadataEntry key="_HKPrivateDeepBreathingEndReason" value="1"/>
 </Record>
 <Record type="HKCategoryTypeIdentifierMindfulSession" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" creationDate="2016-12-07 21:49:01 -0800" startDate="2016-12-07 21:47:58 -0800" endDate="2016-12-07 21:48:58 -0800">
  <MetadataEntry key="_HKPrivateDeepBreathingEndReason" value="1"/>
  <MetadataEntry key="_HKPrivateDeepBreathingFinalHeartRate" value="62.266357421875"/>
 </Record>
 <Workout workoutActivityType="HKWorkoutActivityTypeRunning" duration="30.7799301336209" durationUnit="min" totalDistance="3.256991668655052" totalDistanceUnit="mi" totalEnergyBurned="378.3760000000004" totalEnergyBurnedUnit="kcal" sourceName="Andrew’s Apple Watch" sourceVersion="3.1" creationDate="2016-12-06 17:43:39 -0800" startDate="2016-12-06 17:12:44 -0800" endDate="2016-12-06 17:43:30 -0800">
  <MetadataEntry key="HKIndoorWorkout" value="1"/>
 </Workout>
 <ActivitySummary dateComponents="1969-12-30" activeEnergyBurned="0" activeEnergyBurnedGoal="0" activeEnergyBurnedUnit="kcal" appleExerciseTime="0" appleExerciseTimeGoal="30" appleStandHours="0" appleStandHoursGoal="12"/>
 <ActivitySummary dateComponents="1969-12-31" activeEnergyBurned="0" activeEnergyBurnedGoal="0" activeEnergyBurnedUnit="kcal" appleExerciseTime="0" appleExerciseTimeGoal="30" appleStandHours="0" appleStandHoursGoal="12"/>
 <ActivitySummary dateComponents="2016-11-23" activeEnergyBurned="0" activeEnergyBurnedGoal="0" activeEnergyBurnedUnit="kcal" appleExerciseTime="0" appleExerciseTimeGoal="30" appleStandHours="0" appleStandHoursGoal="12"/>
 <ActivitySummary dateComponents="2016-11-24" activeEnergyBurned="1.201" activeEnergyBurnedGoal="0" activeEnergyBurnedUnit="kcal" appleExerciseTime="0" appleExerciseTimeGoal="30" appleStandHours="0" appleStandHoursGoal="12"/>
 <ActivitySummary dateComponents="2016-12-04" activeEnergyBurned="0" activeEnergyBurnedGoal="0" activeEnergyBurnedUnit="kcal" appleExerciseTime="0" appleExerciseTimeGoal="30" appleStandHours="0" appleStandHoursGoal="12"/>
 <ActivitySummary dateComponents="2016-12-05" activeEnergyBurned="0" activeEnergyBurnedGoal="1080" activeEnergyBurnedUnit="kcal" appleExerciseTime="0" appleExerciseTimeGoal="30" appleStandHours="0" appleStandHoursGoal="12"/>
 <ActivitySummary dateComponents="2016-12-06" activeEnergyBurned="617.365" activeEnergyBurnedGoal="1080" activeEnergyBurnedUnit="kcal" appleExerciseTime="43" appleExerciseTimeGoal="30" appleStandHours="7" appleStandHoursGoal="12"/>
 <ActivitySummary dateComponents="2016-12-07" activeEnergyBurned="414.526" activeEnergyBurnedGoal="1080" activeEnergyBurnedUnit="kcal" appleExerciseTime="23" appleExerciseTimeGoal="30" appleStandHours="17" appleStandHoursGoal="12"/>
 <ActivitySummary dateComponents="2016-12-08" activeEnergyBurned="148.418" activeEnergyBurnedGoal="1080" activeEnergyBurnedUnit="kcal" appleExerciseTime="9" appleExerciseTimeGoal="30" appleStandHours="6" appleStandHoursGoal="12"/>
</HealthData>
